export const tableHeading = [
  "Practice",
  "Contact Person",
  "Contact Number",
  "Email",
  "Practice Status",
  "Created date",
  "Modified date",
  "Created By",
  "Modified By",
];

export const tableData = [
  {
    id: 1,
    practice: "JIP",
    contactPerson: "Mithun",
    contactNumber: "+91 78478 98323",
    email: "mithun@techindia.in",
    practiceStatus: true,
    createdDate: "01/11/2020 02:32",
    modifiedDate: "01/11/2020 02:32",
    createdBy: "Evan Flores",
    modifiedBy: "Evan Flores",
  },
  {
    id: 2,
    practice: "Apollo",
    contactPerson: "Satish",
    contactNumber: "+91 98478 98322",
    email: "satish@apollo.in",
    practiceStatus: true,
    createdDate: "01/11/2020 02:32",
    modifiedDate: "01/11/2020 02:32",
    createdBy: "Arlene Wilson",
    modifiedBy: "Arlene Wilson",
  },
  {
    id: 3,
    practice: "MGM",
    contactPerson: "Rakesh",
    contactNumber: "+91 97478 98326",
    email: "rakesh@apollo.in",
    practiceStatus: true,
    createdDate: "01/11/2020 02:32",
    modifiedDate: "01/11/2020 02:32",
    createdBy: "Evan Flores",
    modifiedBy: "Evan Flores",
  },
];
